version: 2
model:
  unet:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    subfolder: "unet"
  vae:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    subfolder: "vae"
  clip:
    pretrained_model_name_or_path: "openai/clip-vit-large-patch14"
  tokenizer:
    pretrained_model_name_or_path: "openai/clip-vit-large-patch14"
  noise_scheduler:
    name: "LMSDiscreteScheduler"
    args:
      num_train_timesteps: 1500
      steps_offset: 1
data:
  path: "/content/drive/MyDrive/projects/metcs777/train_set_large_Harward_Metroplitan_Smithsonian/"
  # Other possible type are imagefolder, csv, ... (which is coming from huggingface load_dataset())
  type: "parquet"
training:
  learning_rate: 0.01
  batch_size: 4
  epochs: 10
  max_train_steps: 200
output:
  model: "/content/drive/MyDrive/projects/metcs777/output/"
  log: "/content/drive/MyDrive/projects/metcs777/log/"
